### PR TITLE
add option 2 points for small cities

### PR DESCRIPTION
**Pull request by mahlzahn**
Because we play it usually like that, I added a rule option for small cities to be counted as 2 points as in official rules before 2002 (see e.g. https://www.carc-forum.de/viewtopic.php?f=277&t=504 ).
carc-1

### CODE REVIEW

**Comment by mahlzahn** [comment]
Just saw issue #250 about this ;)

**Comment by farin** [comment]
I would rather extract rule to plugin because this is very old riule.
Anyway you can use custom buld meantime and it should work if all parties use it.

I excepting next release at beginning of 2020, i am quite busy now, but i will try address this in some way.

**Comment by farin** [comment]
feature will be added to 5.0.0

**Comment by farin** [comment]
readdedd under original name 165de0a2ea84480f8b29f1628cf1221a604f53ff

**Pull request closed without merging**
