### PR TITLE
#112

### PR DESCRIPTION
**Pull request by XBukaX**
I added a messageBox warning a player when he decides not to use his Abbey tile on the end of the game. Then he can use it or pass anyway.

### CODE REVIEW

**Comment by khalidqasrawi** [comment]
Neat update.  I often miss the placing the Abbey tile because I skip through it without checking that it is my last move.

I have a suggestion which is to add extra constructors to SelectActionEvent which have *passWarning* as an extra parameter and then to default the value in the existing constructors.  That would make the change more limited in the number of files that it touches.  Just my thoughts but I'm not so sure on the style here.

**Comment by farin** [comment]
i think it's not needed to modify SelectActionEvent etc. I would be better check it higher on UI level like confirmation before placement on farm. (still there can be a helper on AbbeyCapability class)

**Comment by XBukaX** [comment]
OK, I'll try to move it higher, like the farm meeple placement confirmation.

**Comment by XBukaX** [comment]
Now there is a seperate event for a warning just like there is one for a confirm request. I hope it's better now.

**Pull request merged**
