### PR TITLE
add dutch translation (#93)

### PR DESCRIPTION
**Pull request by fatsu**

### CODE REVIEW

**Comment by farin** [comment]
perfect, thanks

**Comment by farin** [comment]
@fatsu Hi
May I request instant translation before release? I added resume
feature to online server besides. If you end application you can resume next time.

I also realized that some string still missing in original nl.po file (maybe it was translated according to outdated po) Could you please check it?

**Comment by fatsu** [comment]
@farin 
I see that you changed all *.po files (f0497ddd9fd388f6e05679c9d41f014068c2e25d), except the nl.po. So I assume that the messages you would like me to have a look at are not yet included?

**Comment by farin** [comment]
@fatsu sorry, i missing the new one nl.po in https://github.com/farin/JCloisterZone/blob/master/BUILDING.md

now it shoild be updated correctly in master. To avoid confusion. I see missing following keys
http://jcloisterzone.com/s/poedit.jpg

**Pull request merged**
