### PR TITLE
Issue #193 - Purist mode

### PR DESCRIPTION
**Pull request by XBukaX**
An option (rule) to play JCZ in a mode resembling what we have in a plain tabletop game. It includes:
-disabled Farm Hints and Projected Scores
-counter of remaining tiles doesn't show an exact value until there's few of them left (12)
-there's no highlighting of acceptable tile locations
-these acceptable tile locations could still be spotted by players by projecting or not an image of a tile when cursor entered a corresponding space, so I also changed it to always project that image
-there's no auto-rotation of a tile

That's just a special rule for those who want to play tournament-like games and it doesn't change a regular play.

### CODE REVIEW

**Comment by farin** [comment]
Hi 
I am not only sure about disabling auto rotation, I think it's not bring you any remarkable additional information. The reason for such feature is making user interface more convenient and save unnecessary clicks.

**Comment by farin** [comment]
second thing, showing >12 or exact number is imho not good.

You lose complete information about game progress. In real game, you know if you are in half of if there is last 20 tiles.  Moreover, lot of players play without bag and it such case you can get real number of remaining tiles.

**Comment by farin** [comment]
referencing original discussion 
http://www.carcassonnecentral.com/community/index.php?topic=855.msg10827#msg10827

**Comment by XBukaX** [comment]
I must agree about tile counter. It could be refactored to show approximate progress in a game, but I think it will be easier to just leave it the way it was before.

Auto rotation just didn't seem natural after changes. When I disabled highlighting possible tile placements, I noticed the fact that a preview image is shown only when the cursor is in one of these placements, still somehow unveiling them. So I changed it to always show the preview image in any square the cursor is in, but then auto rotation still happened in possible tile placements and looked somehow weird. But maybe I'm too puristic. Simplicity of interface should be a priority.

**Comment by Hueristic** [comment]
Creating an option for anything should not be a problem and if adding a preset for "Purist mode" that auto changed this subset then that should not be a point of contention either. 

One thing is the main options page is getting cluttered so an advanced options one should be added with these type choices placed in that sub menu.

Don't forget that alot of n00bs are just learning on this program and get confused with too many choices.

**Comment by Eldenroot** [comment]
+1, I hope it will be merged and available in the next release :)

**Comment by Hueristic** [comment]
readme file for actual changes made, just source is a pita.

**Comment by x-iso** [comment]
For tile counter, I think just a progress bar would work well, revealing exact number only when 12 tiles are left. This way it allows to see only approximate 'volume' of tiles left.

**Comment by farin** [comment]
I am keeping feature in mind during current major ui rewritre

**Pull request closed without merging**
