### PR TITLE
Solution for: Allow player for resign

### PR DESCRIPTION
**Pull request by wTendera**
One more fix probably needed, after resigning player move should be skipped

### CODE REVIEW

**Comment by farin** [comment]
basically it's ok, 
but there are expansions based on player count - at least bazaar draws tile for each player - it must draw only tiles for unresigned players

**Comment by wTendera** [comment]
well i checked it and while bidding, tiles are drawn only for unresigned players. (bazzar uses getNextPlayer method that I changed)

correct me if I'm wrong, I'm rather newbie in carcassonne :)

**Comment by farin** [comment]
this must be changed
https://github.com/farin/JCloisterZone/blob/master/src/main/java/com/jcloisterzone/game/phase/BazaarPhase.java#L49

and also all game.getAllPlayers() must be checked.

Also save game should be updated to persist resign flag, but it's minor issue and i can do it at my own.

**Comment by farin** [comment]
but it strange  you said it works coretly, I can't try it myself now

**Comment by wTendera** [comment]
I fixed this line

About testing i just made new game bridges castles and baazar and checked if baazar switched correctly between player.

Any other changes needed before merge?

**Comment by Hueristic** [comment]
Should be option for AI to take over resigned player.

**Comment by farin** [comment]
@Hueristic i think it's unwanted complication. At very beginning I hase same idea, but I am not sure if there is any benefit. Let's keep it simple for now.

@wTendera Finally I have to spent some time with JCZ. Looked ar your changes. I have two notes
- resign button - please no tihs way - it's esge case, menu is proper place for it
- impl is still not so easy - information about must be propagate throug network to other clients and more over it would be nice if save game handle this to

anyway, i will manage itself, i think I can do it faster and properly. So I push this stuff to resign branch and will finish it myself.

**Comment by Hueristic** [comment]
I'm not sure if you guys are just talking about bazaar games (which I've never played) but on other option games I don't think your taking into effect mutiplayer games as opposed to heads up. 

When 4 people are playing and one person has to leave or quits then the game just hangs until the person who left leaves. That stops the game and no-one can finish it. So I see no reason why when someone chooses "leave game" or add a resign option then the AI takes over their turn or their turn is just skipped. As it is now the entire game is ruined for the rest of the players.

**Comment by Eldenroot** [comment]
+1, I hope it will be merged and available in the next release :)

**Comment by Hueristic** [comment]
Reason why AI should be option to take over Resigned player is that one player can resign to give another player an advantage. This is a critical option in competitive matches.

**Comment by farin** [comment]
I want to finish this to 4.1 (planned to beginning of January)

**Comment by farin** [comment]
no longer valid for new architecture (but sill in TODO list)

**Pull request closed without merging**
