### PR TITLE
Solution for: enter exclusive full screen mode

### PR DESCRIPTION
**Pull request by wTendera**
Key biding for entering full screen probably should be changed from 0, if you know on which combination/key you want it please leave a commeny

### CODE REVIEW

**Comment by farin** [comment]
F11 is imho traditional full screen key 

I am just curious why it's is catched only on GameView
GameView means running game, i think you should be able to toggle this in any case. Which means it should be rather related to Client itself

**Comment by wTendera** [comment]
i changed it to f11, I have chosen game view because as far as i understand code, each view has it's own key listeners so it either requires good refactor (for global shortcuts independent from view) or adding shortcut in each view (quite ugly huh?) or catching event in client and hoping no one will catch the same event in other view (I can't predict what will happen than)

**Comment by farin** [comment]
View is abstraction for "root component", app menu state (disabling/enabling items) and own key listener.
Each view has own key listeners because each view has also own shortcuts related only for such view.
I didn't want to care about game specific shortcuts on global level - like TAB, which toggle actions during game.
But full screen is slightly different. You can catch it on client and prevent bubbling. In any case no view should than bind on that key stroke. but it's quite natural, F11 is global keystroke.

**Comment by wTendera** [comment]
done

**Comment by Hueristic** [comment]
F11 for Fullscreen with no menu bar or border.

I thought switching between whatever size windows and full size window was Alt-Shift-Enter.
Apparently it was (http://blogs.msdn.com/b/saraford/archive/2005/03/29/did-you-know-how-to-use-full-screen-mode-shift-alt-enter.aspx), I'm getting old. 
Now it's that stupid windows button with an up or down arrow. Hate that key, I rip it out of keyboards. :)

BTW, ⊞ Win+↓ and ⊞ Win+↑ work fine. For Min and maxing windowed mode.

https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts

**Comment by wTendera** [comment]
so right now full screen is okay (I'm testing on mac, correct me if im wrong :) )

you want me to change(/add) shortcut with Win+↓ and ⊞ Win+↑ ? (btw ⊞ is cmd?)

**Comment by Hueristic** [comment]
⊞ just denotes windows button on windows, redundant when used as "⊞ Win", "⊞ Win" is actually one key.

"⊞ Win +↓" and "⊞ Win+↑" already work fine.

:⌘ Cmd+CTRL+F" is Mac default it should work as it's built into the libraries but adding "F11" globally won't hurt anything and it's alot easier to remember! 
It seems the industry is moving to that anyway as most games have always been "f11" to change mode between windowed mode and fullscreen

**Comment by wTendera** [comment]
ok now I'm confused :D

So F11 is okay, but you also want "⊞ Win +↓" and "⊞ Win+↑"  for windows and :⌘ Cmd+CTRL+F for macbook? 

anything else before merge?

**Comment by Hueristic** [comment]
Exclusive Full screen mode has no menu's or border. I have always been unable to get exclusive full screen with any method, F11 would be nice.
"⊞ Win +↓" and "⊞ Win+↑" for windows and ":⌘ Cmd+CTRL+F" should already work for maximize window and default windows size toggle (built in default libraries), I'm not sure which O.S. versions this is supported on so it couldn't hurt to have those hard coded as well if it is not too much of a bother. If it is already in the libraries of all supported O.S.'s then it would be moot. should be added to the documentation if it's not there.

**Comment by farin** [comment]
let's leave fullscreen to UI rewrite (5.0)

**Pull request closed without merging**
